ref:
  species: "Mus_musculus"
  build: "GRCm39"
  release: "113"
  genome: 'mm39'
  flavor: "chr"

experiment:
  name: "spliceat_preprint"
  biotype: "protein_coding"
  max_transcript_support_level: 3
  strandedness: "reverse"
  readlen: 150
  groups: [ "control", "treated" ] 


samples: "input/design.tsv"


leafcutter:
  activate: True

majiq:
  activate: True
  license: "config/majiq/majiq_license_academic_official.lic"

whippet:
  activate: True
  bam_min_reads: 100