ref:
  species: "Mus_musculus"
  build: "GRCm39"
  release: "113"
  genome: 'mm39'
  flavor: "chr"

experiment:
  name: "spliceat_preprint"
  biotype: "protein_coding"
  max_transcript_support_level: 3
  strandedness: "reverse"
  readlen: 150
  groups: [ "control", "treated" ] 


samples: "input/design.tsv"


leafcutter:
  activate: True
  max_intron_size: 500000
  cluster_support_min: 50

majiq:
  activate: True
  license: "config/majiq/majiq_license_academic_official.lic"

whippet:
  activate: True
  bam_groups:
  - "treated"
  bam_min_reads: 20

stringtie:
  activate: True
  threads: 4
  strand: rf
  min_juncs: 20